version: '3'
services:
  # 数据库
  pg:
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - './volumes/pg:/var/lib/postgresql/data'
    ports:
      - 65432:5432
    environment:
      - POSTGRES_USER=gotest # 用户名
      - POSTGRES_PASSWORD=gotest # 数据库密码
      - POSTGRES_DB=gotest # 数据库名

  # 缓存
  redis:
    image: redis:6.2.3-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - './volumes/redis:/data'
    #    environment:
    #      - REDIS_PASSWORD=password
    #    command: [ "redis-server", "--requirepass", "password" ]
    command: ['redis-server']
