version: '3'
services:
  user-api:
    image: alpine:3.12
    restart: always
    working_dir: /app
    volumes:
      - './scheduled_server:/app/scheduled_server'
    environment:
      - MACHINE_ID=0
      - GO_MOD=development
      # database
      - DB_HOST=172.18.71.172
      - DB_PORT=65432
      - DB_DRIVER=postgres
      - DB_NAME=gotest
      - DB_USERNAME=gotest
      - DB_PASSWORD=gotest
      # redis
      - REDIS_SERVER=172.18.71.172
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    command: ['./scheduled_server', 'start']
