version: '3'
services:
  user-api:
    image: alpine:3.12
    restart: always
    ports:
      - 9000:80
    working_dir: /app
    volumes:
      - './user_server:/app/user_server'
    environment:
      - MACHINE_ID=0
      - GO_MOD=development
      - TOKEN_SECRET_KEY=44JodlDOWk13f8a0&fKSDI*AP
      # database
      - DB_HOST=172.18.71.172
      - DB_PORT=65432
      - DB_DRIVER=postgres
      - DB_NAME=gotest
      - DB_USERNAME=gotest
      - DB_PASSWORD=gotest
      # redis
      - REDIS_SERVER=172.18.71.172
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      # message queue
      - MSG_QUEUE_SERVER=172.18.71.172
      - MSG_QUEUE_PORT=4150
      # wechat
      - WECHAT_APP_ID=xxx
      - WECHAT_SECRET=xxx
    command: ['./user_server', 'start']
