version: '3'
services:
  admin-api:
    image: alpine:3.12
    restart: always
    ports:
      - 9091:80
    working_dir: /app
    volumes:
      - './admin_server:/app/admin_server'
    environment:
      - MACHINE_ID=0
      - GO_MOD=development
      - TOKEN_SECRET_KEY=44JodlDOWk13f8a0&fKSDI*AP
      # database
      - DB_HOST=172.18.71.172
      - DB_PORT=65432
      - DB_DRIVER=postgres
      - DB_NAME=gotest
      - DB_USERNAME=gotest
      - DB_PASSWORD=gotest
      # redis
      - REDIS_SERVER=172.18.71.172
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      # message queue
      - MSG_QUEUE_SERVER=172.18.71.172
      - MSG_QUEUE_PORT=4150
      # push
      - ONE_SIGNAL_APP_ID=xxx
      - ONE_SIGNAL_REST_API_KEY=xxx
    command: ['./admin_server', 'start']
