// Copyright 2019 Axetroy. All rights reserved. MIT license.
package exception

var (
	Unknown                  = New("未知错误", 0)
	InvalidParams            = New("参数不正确", 0)
	NoData                   = New("找不到数据", 0)
	UserNotLogin             = New("请先登陆", 100000)
	InvalidAuth              = New("无效的身份认证方式", 100000)
	InvalidToken             = New("无效的身份令牌", 100000)
	TokenExpired             = New("身份令牌已过期", 100000)
	RequirePassword          = New("请输入密码", 0)
	RequirePayPassword       = New("请输入交易密码", 0)
	InvalidPassword          = New("密码错误", 0)
	InvalidAccountOrPassword = New("账号或密码错误", 0)
	InvalidActiveCode        = New("激活链接已超时", 0)
	UserHaveActive           = New("用户已激活", 0)
	PasswordDuplicate        = New("新密码和旧密码不能相同", 0)
	InvalidInviteCode        = New("无效的邀请码", 0)
	PayPasswordSet           = New("交易密码已设置", 0)
	PayPasswordNotSet        = New("请先设置交易密码", 0)
	NoPermission             = New("没有权限", 0)
	InvalidConfirmPassword   = New("两次输入密码不一致", 0)
	InvalidOldPassword       = New("旧密码错误", 0)
	EmptyList                = New("sql: no rows in result set", 0)
)
